apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flextopos.flextopo.baichuan-inc.com
spec:
  group: flextopo.baichuan-inc.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                nodes:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
                      attributes:
                        type: object
                        additionalProperties: true
                edges:
                  type: array
                  items:
                    type: object
                    properties:
                      source:
                        type: string
                      target:
                        type: string
                      type:
                        type: string
            status:
              type: object
              additionalProperties: true
      subresources:
        status: {}
  scope: Cluster
  names:
    plural: flextopos
    singular: flextopo
    kind: FlexTopo
    shortNames:
      - ftopo